// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Pokemon struct {
	ID                 pgtype.UUID
	Name               string
	Height             pgtype.Int4
	Weight             pgtype.Int4
	NationalDexOrder   int32
	BaseExperience     pgtype.Int4
	IsDefault          bool
	SortOrder          int32
	PrimaryType        int32
	SecondaryType      pgtype.Int4
	BaseAttack         int32
	BaseDefense        int32
	BaseSpecialAttack  int32
	BaseSpecialDefense int32
	BaseSpeed          int32
	BaseHp             int32
}

type Type struct {
	ID   int32
	Name string
}

type TypeEffectiveness struct {
	AttackingTypeID int32
	DefendingTypeID int32
	Multiplier      pgtype.Numeric
}
